apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
spec:
  project: kargo
  syncPolicy:
    automated: {}
  source:
    repoURL: https://github.com/34fathombelow/kargo_example.git
    targetRevision: main
    path: apps
    directory:
      recurse: true
  destination:
    name: in-cluster
    namespace: argocd
