apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - stage: test
      - stage: uat
      - stage: prod-useast
      - stage: prod-uswest
  template:
    metadata:
      name: kargo-guestbook-{{stage}}
      annotations:
        kargo.akuity.io/authorized-stage: guestbook:{{stage}}
    spec:
      project: kargo
      source:
        repoURL: https://github.com/34fathombelow/kargo_example.git
        targetRevision: stage/{{stage}}
        path: guestbook/stages/{{stage}}
      destination:
        name: kargo
        namespace: kargo-guestbook-{{stage}}
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
