apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-guestbook
spec:
  project: kargo
  source:
    repoURL: https://github.com/34fathombelow/kargo_example.git
    path: kargo
  destination:
    server: https://tf9h2fbpefdshpb9.kargo.test.akuity.io/
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
