apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-guestbook
spec:
  project: default
  source:
    repoURL: https://github.com/34fathombelow/kargo_example.git
    path: kargo
  destination:
    name: kargo1
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
